### ISSUE TITLE
Delta calculations slightly off

### ISSUE THREAD

**Issue by Untellable** [gerrymandr/spanning_trees#3]
It seems like the random_walk function sometimes returns districts whose populations vary slightly more than they should given delta.
I ran it with delta = .05 and got 3 districts with these populations: [58614, 61405, 55024]
The ideal district size is 58347.6, so all districts should be within (55430.28, 61265.05) 
but the second district is too big and the third is too small.

**Comment by Untellable** [comment]
I get too a too wide population spread about every other run

**Comment by ElleNajt** [comment]
This should be working now - there was a minus where there should have been a /. (And various other propagating errors.) 

Thanks for pointing this out!
